version: '3.7'

services:
  webapp:
    container_name: studay
    build: .
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    networks:
      - studay

    environment:
      - NODE_ENV=development
      - VIRTUAL_HOST=www.studay.test
      - VIRTUAL_PORT=3000
      - VIRTUAL_PROTO=http

networks:
  studay:
    external:
      name: studay
